import keyMirror from 'keymirror';

export const reduxActions = keyMirror({
  FETCH_POKEMONS: 'FETCH_POKEMONS',
  FETCH_POKEMONS_BY_TYPE: 'FETCH_POKEMONS_BY_TYPE',
  SET_FILTER: 'SET_FILTER',
  FETCH_POKEMON: 'FETCH_POKEMON',
  CLEAR_POKEMONLIST: 'CLEAR_POKEMONLIST',
  FETCH_POKEMON_EVOLUTION: 'FETCH_POKEMON_EVOLUTION',
});
